---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-config
  namespace: flux-system
spec:
  dependsOn:
  - name: tailscale-operator
  path: ./k8s/infrastructure/configs/tailscale/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
