---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner/
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
  install:
    createNamespace: true
  interval: 24h
  targetNamespace: local-path-storage
  timeout: 10m0s
  values:
    storageClass:
      default: true
      defaultVolumeType: local
      nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
        - /var/local-path-provisioner
      volumeBindingMode: WaitForFirstConsumer
