apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: flux-system
  name: external-secrets
spec:
  interval: 24h
  targetNamespace: external-secrets
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chartRef:
    kind: OCIRepository
    namespace: flux-system
    name: external-secrets
