apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  ref:
    tag: 2.10.0
