---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
    namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 24h
  targetNamespace: cnpg-system
  timeout: 10m0s
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      podMonitorEnabled: true
