---
{
  apiVersion: "batch/v1",
  kind: "CronJob",
  metadata: {
    name: "cleanup",
  },
  spec: {
    schedule: "@daily",
    jobTemplate: {
      spec: {
        template: {
          spec: {
            restartPolicy: "Never",
            containers: [{
              name: "cleanup",
              image: "miniflux",
              command: [
                "miniflux",
                "-run-cleanup-tasks",
              ],
            }],
          },
        },
      },
    },
  },
}
