---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "container",
    annotations: {
      config.kubernetes.io/local-config: "true",
    },
  },
  data: {
    securityContext: {
      runAsNonRoot: true,
      allowPrivilegeEscalation: false,
      readOnlyRootFilesystem: true,
      capabilities: {
        drop: [
          "ALL",
        ],
      },
    },
    envFrom: [{
      configMapRef: {
        name: "env",
      },
    }],
    volumeMounts: [{
      name: "db",
      mountPath: "/run/secrets/db",
      readOnly: true,
    }],
  },
}
