---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "pod",
    annotations: {
      config.kubernetes.io/local-config: "true",
    },
  },
  data: {
    volumes: [{
      name: "db",
      secret: {
        secretName: "miniflux-pg-app",
        items: [{
          key: "fqdn-uri",
          path: "fqdn-uri",
        }],
        optional: false,
      },
    }],
    automountServiceAccountToken: false,
  },
}
