---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: flux-system
  install:
    crds: CreateReplace
  interval: 24h
  targetNamespace: monitoring
  timeout: 10m0s
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      alertmanagerSpec:
        secrets:
        - discord
      config:
        receivers:
        - name: "null"
        - discord_configs:
          - webhook_url_file: /etc/alertmanager/secrets/discord/webhook_url
          name: discord
        route:
          receiver: discord
    defaultRules:
      rules:
        etcd: false
        kubeApiserverAvailability: false
        kubeControllerManager: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
    grafana:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
