---
{
  apiVersion: "source.toolkit.fluxcd.io/v1",
  kind: "OCIRepository",
  metadata: {
    name: "kube-prometheus-stack",
    namespace: "flux-system",
  },
  spec: {
    interval: "24h",
    layerSelector: {
      mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
      operation: "copy",
    },
    url: "oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack",
    ref: {
      tag: "92.2.0",
    },
  },
}
