apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  namespace: external-secrets
  name: oci
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.uk-london-1.ervkmzf2aaak4.abwgiljtce5aox5wuda65owvcx4phncmcjgroydqb4mfuxqu7e6ukzaxqw3q
      region: uk-london-1
      principalType: InstancePrincipal
