---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: tailscale
  name: operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci
  target:
    name: operator-oauth
  dataFrom:
  - extract:
      key: tailscale_operator
