apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- source.toolkit.fluxcd.io_HelmRepository_tailscale.yaml
- helm.toolkit.fluxcd.io_HelmRelease_tailscale-operator.yaml
- externalsecret.external-secrets.io_operator-oauth.yaml
