---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "./kustomization.kustomize.toolkit.fluxcd.io_external-secrets.yaml",
    "./kustomization.kustomize.toolkit.fluxcd.io_tailscale-operator.yaml",
    "./kustomization.kustomize.toolkit.fluxcd.io_kube-prometheus-stack.yaml",
    "./kustomization.kustomize.toolkit.fluxcd.io_metrics-server.yaml",
    "./kustomization.kustomize.toolkit.fluxcd.io_longhorn.yaml",
    "./local-path-provisioner/",
  ],
}
